### ISSUE TITLE
Newer version?

### ISSUE THREAD

**Issue by ghost** [lutris/dgvoodoo2#1]
http://dege.fw.hu/dgVoodoo2/dgVoodoo2/

dgVoodoo v2.7 (D3D12 support added, improved fast videomemory access) + 13 releases with optimizations and fixes after that.

Latest: dgVoodoo v2.78

**Comment by tannisroot** [comment]
I have graphical bugs with newer versions of dgvoodoo in The Sims (2000), perhaps if they are fixed i will update that.
i'm going to put the bug report to Dege on my to do list

**Comment by glu8716** [comment]
+1 for this. I use dgVoodoo for another game. It's true that 2.64 version works fine on my case too, but it still would be nice to have at least the latest version (v2.78.1) for those who use it without problems
